
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.hellscraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.hellscraft.block.WaxedBlockOfCornBlock;
import net.mcreator.hellscraft.block.StrippedPissStemBlock;
import net.mcreator.hellscraft.block.StrippedDarkwoodLogBlock;
import net.mcreator.hellscraft.block.StoneBlockBlock;
import net.mcreator.hellscraft.block.SpawnEggOreBlock;
import net.mcreator.hellscraft.block.SmoothHardspiceSlabBlock;
import net.mcreator.hellscraft.block.SmoothHardspiceBlock;
import net.mcreator.hellscraft.block.SmoothGreenstoneSlabBlock;
import net.mcreator.hellscraft.block.SmoothGreenstoneBlock;
import net.mcreator.hellscraft.block.SaltLampBlock;
import net.mcreator.hellscraft.block.RockSaltBlock;
import net.mcreator.hellscraft.block.RockButterBlock;
import net.mcreator.hellscraft.block.QuicksandBlock;
import net.mcreator.hellscraft.block.PressBlock;
import net.mcreator.hellscraft.block.PressABlock;
import net.mcreator.hellscraft.block.PolishedPopcornWallBlock;
import net.mcreator.hellscraft.block.PolishedPopcornStairsBlock;
import net.mcreator.hellscraft.block.PolishedPopcornSlabBlock;
import net.mcreator.hellscraft.block.PolishedCornWallBlock;
import net.mcreator.hellscraft.block.PolishedCornStairsBlock;
import net.mcreator.hellscraft.block.PolishedCornSlabBlock;
import net.mcreator.hellscraft.block.PolishedBlockOfPopcornBlock;
import net.mcreator.hellscraft.block.PolishedBlockOfCornBlock;
import net.mcreator.hellscraft.block.PissWartBlockBlock;
import net.mcreator.hellscraft.block.PissStemBlock;
import net.mcreator.hellscraft.block.PissRootsBlock;
import net.mcreator.hellscraft.block.PissPressurePlateBlock;
import net.mcreator.hellscraft.block.PissPlanksBlock;
import net.mcreator.hellscraft.block.PissPlankTrapdoorBlock;
import net.mcreator.hellscraft.block.PissPlankStairsBlock;
import net.mcreator.hellscraft.block.PissPlankSlabBlock;
import net.mcreator.hellscraft.block.PissPlankFenceGateBlock;
import net.mcreator.hellscraft.block.PissPlankFenceBlock;
import net.mcreator.hellscraft.block.PissPlankDoorBlock;
import net.mcreator.hellscraft.block.PissNyliumBlock;
import net.mcreator.hellscraft.block.PissMushroomBlock;
import net.mcreator.hellscraft.block.PissButtonBlock;
import net.mcreator.hellscraft.block.NetherspiceBlockBlock;
import net.mcreator.hellscraft.block.KidneystoneBlock;
import net.mcreator.hellscraft.block.HardspiceStairsBlock;
import net.mcreator.hellscraft.block.HardspiceSlabBlock;
import net.mcreator.hellscraft.block.HardspiceBricksBlock;
import net.mcreator.hellscraft.block.HardspiceBrickWallBlock;
import net.mcreator.hellscraft.block.HardspiceBrickStairsBlock;
import net.mcreator.hellscraft.block.HardspiceBrickSlabBlock;
import net.mcreator.hellscraft.block.HardspiceBlock;
import net.mcreator.hellscraft.block.GunkBlock;
import net.mcreator.hellscraft.block.GreenstoneStairsBlock;
import net.mcreator.hellscraft.block.GreenstoneSlabBlock;
import net.mcreator.hellscraft.block.GreenstoneBricksBlock;
import net.mcreator.hellscraft.block.GreenstoneBrickWallBlock;
import net.mcreator.hellscraft.block.GreenstoneBrickStairsBlock;
import net.mcreator.hellscraft.block.GreenstoneBrickSlabBlock;
import net.mcreator.hellscraft.block.GreenstoneBlock;
import net.mcreator.hellscraft.block.FishmetalBlockBlock;
import net.mcreator.hellscraft.block.DeepslateSpawnEggOreBlock;
import net.mcreator.hellscraft.block.DeeperslateIronOreBlock;
import net.mcreator.hellscraft.block.DeeperslateDiamondOreBlock;
import net.mcreator.hellscraft.block.DeeperslateBlock;
import net.mcreator.hellscraft.block.DarkwoodTrapdoorBlock;
import net.mcreator.hellscraft.block.DarkwoodStairsBlock;
import net.mcreator.hellscraft.block.DarkwoodSlabBlock;
import net.mcreator.hellscraft.block.DarkwoodPressurePlateBlock;
import net.mcreator.hellscraft.block.DarkwoodPlanksBlock;
import net.mcreator.hellscraft.block.DarkwoodLogBlock;
import net.mcreator.hellscraft.block.DarkwoodLeavesBlock;
import net.mcreator.hellscraft.block.DarkwoodFenceGateBlock;
import net.mcreator.hellscraft.block.DarkwoodFenceBlock;
import net.mcreator.hellscraft.block.DarkwoodButtonBlock;
import net.mcreator.hellscraft.block.DarksteelOreBlock;
import net.mcreator.hellscraft.block.DarksteelBlockBlock;
import net.mcreator.hellscraft.block.CornOreBlock;
import net.mcreator.hellscraft.block.CoolerGreenstoneBlock;
import net.mcreator.hellscraft.block.ChiseledGreenstoneBricksBlock;
import net.mcreator.hellscraft.block.CheeseStairsBlock;
import net.mcreator.hellscraft.block.CheeseSlabBlock;
import net.mcreator.hellscraft.block.CheeseFenceBlock;
import net.mcreator.hellscraft.block.BlockOfVillagerBlock;
import net.mcreator.hellscraft.block.BlockOfSaltBlock;
import net.mcreator.hellscraft.block.BlockOfRottenFleshBlock;
import net.mcreator.hellscraft.block.BlockOfPopcornBlock;
import net.mcreator.hellscraft.block.BlockOfPinkSaltBlock;
import net.mcreator.hellscraft.block.BlockOfCornBlock;
import net.mcreator.hellscraft.block.BlockOfCheeseBlock;
import net.mcreator.hellscraft.block.BlockOfButterBlock;
import net.mcreator.hellscraft.block.BlockOfBreadBlock;
import net.mcreator.hellscraft.block.AgingBarrelBlock;
import net.mcreator.hellscraft.HellscraftMod;

public class HellscraftModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, HellscraftMod.MODID);
	public static final RegistryObject<Block> BLOCK_OF_CHEESE = REGISTRY.register("block_of_cheese", () -> new BlockOfCheeseBlock());
	public static final RegistryObject<Block> CHEESE_SLAB = REGISTRY.register("cheese_slab", () -> new CheeseSlabBlock());
	public static final RegistryObject<Block> CHEESE_STAIRS = REGISTRY.register("cheese_stairs", () -> new CheeseStairsBlock());
	public static final RegistryObject<Block> CHEESE_FENCE = REGISTRY.register("cheese_fence", () -> new CheeseFenceBlock());
	public static final RegistryObject<Block> PRESS = REGISTRY.register("press", () -> new PressBlock());
	public static final RegistryObject<Block> AGING_BARREL = REGISTRY.register("aging_barrel", () -> new AgingBarrelBlock());
	public static final RegistryObject<Block> BLOCK_OF_ROTTEN_FLESH = REGISTRY.register("block_of_rotten_flesh", () -> new BlockOfRottenFleshBlock());
	public static final RegistryObject<Block> BLOCK_OF_VILLAGER = REGISTRY.register("block_of_villager", () -> new BlockOfVillagerBlock());
	public static final RegistryObject<Block> QUICKSAND = REGISTRY.register("quicksand", () -> new QuicksandBlock());
	public static final RegistryObject<Block> NETHERSPICE_BLOCK = REGISTRY.register("netherspice_block", () -> new NetherspiceBlockBlock());
	public static final RegistryObject<Block> GUNK = REGISTRY.register("gunk", () -> new GunkBlock());
	public static final RegistryObject<Block> CORN_ORE = REGISTRY.register("corn_ore", () -> new CornOreBlock());
	public static final RegistryObject<Block> DEEPERSLATE = REGISTRY.register("deeperslate", () -> new DeeperslateBlock());
	public static final RegistryObject<Block> DEEPERSLATE_DIAMOND_ORE = REGISTRY.register("deeperslate_diamond_ore", () -> new DeeperslateDiamondOreBlock());
	public static final RegistryObject<Block> DEEPERSLATE_IRON_ORE = REGISTRY.register("deeperslate_iron_ore", () -> new DeeperslateIronOreBlock());
	public static final RegistryObject<Block> DARKSTEEL_ORE = REGISTRY.register("darksteel_ore", () -> new DarksteelOreBlock());
	public static final RegistryObject<Block> GREENSTONE = REGISTRY.register("greenstone", () -> new GreenstoneBlock());
	public static final RegistryObject<Block> GREENSTONE_SLAB = REGISTRY.register("greenstone_slab", () -> new GreenstoneSlabBlock());
	public static final RegistryObject<Block> GREENSTONE_STAIRS = REGISTRY.register("greenstone_stairs", () -> new GreenstoneStairsBlock());
	public static final RegistryObject<Block> GREENSTONE_BRICKS = REGISTRY.register("greenstone_bricks", () -> new GreenstoneBricksBlock());
	public static final RegistryObject<Block> GREENSTONE_BRICK_SLAB = REGISTRY.register("greenstone_brick_slab", () -> new GreenstoneBrickSlabBlock());
	public static final RegistryObject<Block> GREENSTONE_BRICK_STAIRS = REGISTRY.register("greenstone_brick_stairs", () -> new GreenstoneBrickStairsBlock());
	public static final RegistryObject<Block> GREENSTONE_BRICK_WALL = REGISTRY.register("greenstone_brick_wall", () -> new GreenstoneBrickWallBlock());
	public static final RegistryObject<Block> SMOOTH_GREENSTONE = REGISTRY.register("smooth_greenstone", () -> new SmoothGreenstoneBlock());
	public static final RegistryObject<Block> SMOOTH_GREENSTONE_SLAB = REGISTRY.register("smooth_greenstone_slab", () -> new SmoothGreenstoneSlabBlock());
	public static final RegistryObject<Block> CHISELED_GREENSTONE_BRICKS = REGISTRY.register("chiseled_greenstone_bricks", () -> new ChiseledGreenstoneBricksBlock());
	public static final RegistryObject<Block> COOLER_GREENSTONE = REGISTRY.register("cooler_greenstone", () -> new CoolerGreenstoneBlock());
	public static final RegistryObject<Block> PISS_NYLIUM = REGISTRY.register("piss_nylium", () -> new PissNyliumBlock());
	public static final RegistryObject<Block> PISS_STEM = REGISTRY.register("piss_stem", () -> new PissStemBlock());
	public static final RegistryObject<Block> STRIPPED_PISS_STEM = REGISTRY.register("stripped_piss_stem", () -> new StrippedPissStemBlock());
	public static final RegistryObject<Block> PISS_WART_BLOCK = REGISTRY.register("piss_wart_block", () -> new PissWartBlockBlock());
	public static final RegistryObject<Block> PISS_ROOTS = REGISTRY.register("piss_roots", () -> new PissRootsBlock());
	public static final RegistryObject<Block> PISS_MUSHROOM = REGISTRY.register("piss_mushroom", () -> new PissMushroomBlock());
	public static final RegistryObject<Block> KIDNEYSTONE = REGISTRY.register("kidneystone", () -> new KidneystoneBlock());
	public static final RegistryObject<Block> DARKWOOD_LOG = REGISTRY.register("darkwood_log", () -> new DarkwoodLogBlock());
	public static final RegistryObject<Block> SPAWN_EGG_ORE = REGISTRY.register("spawn_egg_ore", () -> new SpawnEggOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_SPAWN_EGG_ORE = REGISTRY.register("deepslate_spawn_egg_ore", () -> new DeepslateSpawnEggOreBlock());
	public static final RegistryObject<Block> ROCK_SALT = REGISTRY.register("rock_salt", () -> new RockSaltBlock());
	public static final RegistryObject<Block> ROCK_BUTTER = REGISTRY.register("rock_butter", () -> new RockButterBlock());
	public static final RegistryObject<Block> FISHMETAL_BLOCK = REGISTRY.register("fishmetal_block", () -> new FishmetalBlockBlock());
	public static final RegistryObject<Block> HARDSPICE = REGISTRY.register("hardspice", () -> new HardspiceBlock());
	public static final RegistryObject<Block> HARDSPICE_SLAB = REGISTRY.register("hardspice_slab", () -> new HardspiceSlabBlock());
	public static final RegistryObject<Block> HARDSPICE_STAIRS = REGISTRY.register("hardspice_stairs", () -> new HardspiceStairsBlock());
	public static final RegistryObject<Block> HARDSPICE_BRICKS = REGISTRY.register("hardspice_bricks", () -> new HardspiceBricksBlock());
	public static final RegistryObject<Block> HARDSPICE_BRICK_SLAB = REGISTRY.register("hardspice_brick_slab", () -> new HardspiceBrickSlabBlock());
	public static final RegistryObject<Block> HARDSPICE_BRICK_STAIRS = REGISTRY.register("hardspice_brick_stairs", () -> new HardspiceBrickStairsBlock());
	public static final RegistryObject<Block> HARDSPICE_BRICK_WALL = REGISTRY.register("hardspice_brick_wall", () -> new HardspiceBrickWallBlock());
	public static final RegistryObject<Block> SMOOTH_HARDSPICE = REGISTRY.register("smooth_hardspice", () -> new SmoothHardspiceBlock());
	public static final RegistryObject<Block> SMOOTH_HARDSPICE_SLAB = REGISTRY.register("smooth_hardspice_slab", () -> new SmoothHardspiceSlabBlock());
	public static final RegistryObject<Block> DARKSTEEL_BLOCK = REGISTRY.register("darksteel_block", () -> new DarksteelBlockBlock());
	public static final RegistryObject<Block> PISS_PLANKS = REGISTRY.register("piss_planks", () -> new PissPlanksBlock());
	public static final RegistryObject<Block> PISS_PLANK_SLAB = REGISTRY.register("piss_plank_slab", () -> new PissPlankSlabBlock());
	public static final RegistryObject<Block> PISS_PLANK_STAIRS = REGISTRY.register("piss_plank_stairs", () -> new PissPlankStairsBlock());
	public static final RegistryObject<Block> PISS_PLANK_FENCE = REGISTRY.register("piss_plank_fence", () -> new PissPlankFenceBlock());
	public static final RegistryObject<Block> PISS_PLANK_TRAPDOOR = REGISTRY.register("piss_plank_trapdoor", () -> new PissPlankTrapdoorBlock());
	public static final RegistryObject<Block> PISS_PLANK_DOOR = REGISTRY.register("piss_plank_door", () -> new PissPlankDoorBlock());
	public static final RegistryObject<Block> PISS_BUTTON = REGISTRY.register("piss_button", () -> new PissButtonBlock());
	public static final RegistryObject<Block> PISS_PRESSURE_PLATE = REGISTRY.register("piss_pressure_plate", () -> new PissPressurePlateBlock());
	public static final RegistryObject<Block> PISS_PLANK_FENCE_GATE = REGISTRY.register("piss_plank_fence_gate", () -> new PissPlankFenceGateBlock());
	public static final RegistryObject<Block> STRIPPED_DARKWOOD_LOG = REGISTRY.register("stripped_darkwood_log", () -> new StrippedDarkwoodLogBlock());
	public static final RegistryObject<Block> DARKWOOD_LEAVES = REGISTRY.register("darkwood_leaves", () -> new DarkwoodLeavesBlock());
	public static final RegistryObject<Block> DARKWOOD_PLANKS = REGISTRY.register("darkwood_planks", () -> new DarkwoodPlanksBlock());
	public static final RegistryObject<Block> DARKWOOD_SLAB = REGISTRY.register("darkwood_slab", () -> new DarkwoodSlabBlock());
	public static final RegistryObject<Block> DARKWOOD_STAIRS = REGISTRY.register("darkwood_stairs", () -> new DarkwoodStairsBlock());
	public static final RegistryObject<Block> DARKWOOD_FENCE = REGISTRY.register("darkwood_fence", () -> new DarkwoodFenceBlock());
	public static final RegistryObject<Block> DARKWOOD_FENCE_GATE = REGISTRY.register("darkwood_fence_gate", () -> new DarkwoodFenceGateBlock());
	public static final RegistryObject<Block> DARKWOOD_TRAPDOOR = REGISTRY.register("darkwood_trapdoor", () -> new DarkwoodTrapdoorBlock());
	public static final RegistryObject<Block> DARKWOOD_BUTTON = REGISTRY.register("darkwood_button", () -> new DarkwoodButtonBlock());
	public static final RegistryObject<Block> DARKWOOD_PRESSURE_PLATE = REGISTRY.register("darkwood_pressure_plate", () -> new DarkwoodPressurePlateBlock());
	public static final RegistryObject<Block> BLOCK_OF_CORN = REGISTRY.register("block_of_corn", () -> new BlockOfCornBlock());
	public static final RegistryObject<Block> WAXED_BLOCK_OF_CORN = REGISTRY.register("waxed_block_of_corn", () -> new WaxedBlockOfCornBlock());
	public static final RegistryObject<Block> POLISHED_BLOCK_OF_CORN = REGISTRY.register("polished_block_of_corn", () -> new PolishedBlockOfCornBlock());
	public static final RegistryObject<Block> POLISHED_CORN_SLAB = REGISTRY.register("polished_corn_slab", () -> new PolishedCornSlabBlock());
	public static final RegistryObject<Block> POLISHED_CORN_STAIRS = REGISTRY.register("polished_corn_stairs", () -> new PolishedCornStairsBlock());
	public static final RegistryObject<Block> POLISHED_CORN_WALL = REGISTRY.register("polished_corn_wall", () -> new PolishedCornWallBlock());
	public static final RegistryObject<Block> BLOCK_OF_POPCORN = REGISTRY.register("block_of_popcorn", () -> new BlockOfPopcornBlock());
	public static final RegistryObject<Block> POLISHED_BLOCK_OF_POPCORN = REGISTRY.register("polished_block_of_popcorn", () -> new PolishedBlockOfPopcornBlock());
	public static final RegistryObject<Block> POLISHED_POPCORN_SLAB = REGISTRY.register("polished_popcorn_slab", () -> new PolishedPopcornSlabBlock());
	public static final RegistryObject<Block> POLISHED_POPCORN_STAIRS = REGISTRY.register("polished_popcorn_stairs", () -> new PolishedPopcornStairsBlock());
	public static final RegistryObject<Block> POLISHED_POPCORN_WALL = REGISTRY.register("polished_popcorn_wall", () -> new PolishedPopcornWallBlock());
	public static final RegistryObject<Block> BLOCK_OF_SALT = REGISTRY.register("block_of_salt", () -> new BlockOfSaltBlock());
	public static final RegistryObject<Block> BLOCK_OF_BUTTER = REGISTRY.register("block_of_butter", () -> new BlockOfButterBlock());
	public static final RegistryObject<Block> BLOCK_OF_PINK_SALT = REGISTRY.register("block_of_pink_salt", () -> new BlockOfPinkSaltBlock());
	public static final RegistryObject<Block> SALT_LAMP = REGISTRY.register("salt_lamp", () -> new SaltLampBlock());
	public static final RegistryObject<Block> PRESS_A = REGISTRY.register("press_a", () -> new PressABlock());
	public static final RegistryObject<Block> STONE_BLOCK = REGISTRY.register("stone_block", () -> new StoneBlockBlock());
	public static final RegistryObject<Block> BLOCK_OF_BREAD = REGISTRY.register("block_of_bread", () -> new BlockOfBreadBlock());
}
