
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.hellscraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.hellscraft.block.WaxedBlockOfCornBlock;
import net.mcreator.hellscraft.block.VantablockBlock;
import net.mcreator.hellscraft.block.UraniumOreBlock;
import net.mcreator.hellscraft.block.StrippedPissStemBlock;
import net.mcreator.hellscraft.block.StrippedDarkwoodLogBlock;
import net.mcreator.hellscraft.block.StoneBlockBlock;
import net.mcreator.hellscraft.block.SpawnEggOreBlock;
import net.mcreator.hellscraft.block.SmoothHardspiceSlabBlock;
import net.mcreator.hellscraft.block.SmoothHardspiceBlock;
import net.mcreator.hellscraft.block.SmoothGreenstoneSlabBlock;
import net.mcreator.hellscraft.block.SmoothGreenstoneBlock;
import net.mcreator.hellscraft.block.SaltLampBlock;
import net.mcreator.hellscraft.block.RockSaltBlock;
import net.mcreator.hellscraft.block.RockButterBlock;
import net.mcreator.hellscraft.block.QuicksandBlock;
import net.mcreator.hellscraft.block.PressBlock;
import net.mcreator.hellscraft.block.PressABlock;
import net.mcreator.hellscraft.block.PolishedPopcornWallBlock;
import net.mcreator.hellscraft.block.PolishedPopcornStairsBlock;
import net.mcreator.hellscraft.block.PolishedPopcornSlabBlock;
import net.mcreator.hellscraft.block.PolishedKidneystoneBlock;
import net.mcreator.hellscraft.block.PolishedEndioriteBlock;
import net.mcreator.hellscraft.block.PolishedEndgraniteBlock;
import net.mcreator.hellscraft.block.PolishedEndersiteBlock;
import net.mcreator.hellscraft.block.PolishedDeeperslateBlock;
import net.mcreator.hellscraft.block.PolishedCornWallBlock;
import net.mcreator.hellscraft.block.PolishedCornStairsBlock;
import net.mcreator.hellscraft.block.PolishedCornSlabBlock;
import net.mcreator.hellscraft.block.PolishedChuckiteStairsBlock;
import net.mcreator.hellscraft.block.PolishedChuckiteSlabBlock;
import net.mcreator.hellscraft.block.PolishedChuckiteBlock;
import net.mcreator.hellscraft.block.PolishedBlockOfPopcornBlock;
import net.mcreator.hellscraft.block.PolishedBlockOfCornBlock;
import net.mcreator.hellscraft.block.PissWartBlockBlock;
import net.mcreator.hellscraft.block.PissStemBlock;
import net.mcreator.hellscraft.block.PissRootsBlock;
import net.mcreator.hellscraft.block.PissPressurePlateBlock;
import net.mcreator.hellscraft.block.PissPlanksBlock;
import net.mcreator.hellscraft.block.PissPlankTrapdoorBlock;
import net.mcreator.hellscraft.block.PissPlankStairsBlock;
import net.mcreator.hellscraft.block.PissPlankSlabBlock;
import net.mcreator.hellscraft.block.PissPlankFenceGateBlock;
import net.mcreator.hellscraft.block.PissPlankFenceBlock;
import net.mcreator.hellscraft.block.PissPlankDoorBlock;
import net.mcreator.hellscraft.block.PissNyliumBlock;
import net.mcreator.hellscraft.block.PissMushroomBlock;
import net.mcreator.hellscraft.block.PissButtonBlock;
import net.mcreator.hellscraft.block.NetherspiceBlockBlock;
import net.mcreator.hellscraft.block.MushrackBlock;
import net.mcreator.hellscraft.block.KidneystoneBricksBlock;
import net.mcreator.hellscraft.block.KidneystoneBlock;
import net.mcreator.hellscraft.block.JeweledDeeperslateBricksBlock;
import net.mcreator.hellscraft.block.JeweledDeeperslateBlock;
import net.mcreator.hellscraft.block.HardspiceStairsBlock;
import net.mcreator.hellscraft.block.HardspiceSlabBlock;
import net.mcreator.hellscraft.block.HardspiceBricksBlock;
import net.mcreator.hellscraft.block.HardspiceBrickWallBlock;
import net.mcreator.hellscraft.block.HardspiceBrickStairsBlock;
import net.mcreator.hellscraft.block.HardspiceBrickSlabBlock;
import net.mcreator.hellscraft.block.HardspiceBlock;
import net.mcreator.hellscraft.block.GunkBlock;
import net.mcreator.hellscraft.block.GrudBlock;
import net.mcreator.hellscraft.block.GreenstoneStairsBlock;
import net.mcreator.hellscraft.block.GreenstoneSlabBlock;
import net.mcreator.hellscraft.block.GreenstoneBricksBlock;
import net.mcreator.hellscraft.block.GreenstoneBrickWallBlock;
import net.mcreator.hellscraft.block.GreenstoneBrickStairsBlock;
import net.mcreator.hellscraft.block.GreenstoneBrickSlabBlock;
import net.mcreator.hellscraft.block.GreenstoneBlock;
import net.mcreator.hellscraft.block.GreaseBlock;
import net.mcreator.hellscraft.block.GildedDeeperslateBricksBlock;
import net.mcreator.hellscraft.block.GildedDeeperslateBlock;
import net.mcreator.hellscraft.block.GalvanicDeepslateBricksBlock;
import net.mcreator.hellscraft.block.GalvanicDeeperslateBlock;
import net.mcreator.hellscraft.block.FishmetalBlockBlock;
import net.mcreator.hellscraft.block.EndioriteBlock;
import net.mcreator.hellscraft.block.EndgraniteBlock;
import net.mcreator.hellscraft.block.EndersiteBlock;
import net.mcreator.hellscraft.block.EndFluidBlock;
import net.mcreator.hellscraft.block.DeepslateUraniumOreBlock;
import net.mcreator.hellscraft.block.DeepslateSpawnEggOreBlock;
import net.mcreator.hellscraft.block.DeeperslateIronOreBlock;
import net.mcreator.hellscraft.block.DeeperslateDiamondOreBlock;
import net.mcreator.hellscraft.block.DeeperslateBricksBlock;
import net.mcreator.hellscraft.block.DeeperslateBrickWallBlock;
import net.mcreator.hellscraft.block.DeeperslateBrickStairsBlock;
import net.mcreator.hellscraft.block.DeeperslateBrickSlabBlock;
import net.mcreator.hellscraft.block.DeeperslateBlock;
import net.mcreator.hellscraft.block.DarkwoodTrapdoorBlock;
import net.mcreator.hellscraft.block.DarkwoodStairsBlock;
import net.mcreator.hellscraft.block.DarkwoodSlabBlock;
import net.mcreator.hellscraft.block.DarkwoodPressurePlateBlock;
import net.mcreator.hellscraft.block.DarkwoodPlanksBlock;
import net.mcreator.hellscraft.block.DarkwoodLogBlock;
import net.mcreator.hellscraft.block.DarkwoodLeavesBlock;
import net.mcreator.hellscraft.block.DarkwoodFenceGateBlock;
import net.mcreator.hellscraft.block.DarkwoodFenceBlock;
import net.mcreator.hellscraft.block.DarkwoodButtonBlock;
import net.mcreator.hellscraft.block.DarksteelOreBlock;
import net.mcreator.hellscraft.block.DarksteelBlockBlock;
import net.mcreator.hellscraft.block.CrackedKidneystoneBricksBlock;
import net.mcreator.hellscraft.block.CornOreBlock;
import net.mcreator.hellscraft.block.CoolerGreenstoneBlock;
import net.mcreator.hellscraft.block.ChuckiteStairsBlock;
import net.mcreator.hellscraft.block.ChuckiteSlabBlock;
import net.mcreator.hellscraft.block.ChuckiteBlock;
import net.mcreator.hellscraft.block.ChisledGalvanicDeeperslateBlock;
import net.mcreator.hellscraft.block.ChiseledKidneystoneBlock;
import net.mcreator.hellscraft.block.ChiseledJeweledDeeperslateBlock;
import net.mcreator.hellscraft.block.ChiseledGreenstoneBricksBlock;
import net.mcreator.hellscraft.block.ChiseledGildedDeeperslateBlock;
import net.mcreator.hellscraft.block.ChiseledDeeperslateBlock;
import net.mcreator.hellscraft.block.CheeseStairsBlock;
import net.mcreator.hellscraft.block.CheeseSlabBlock;
import net.mcreator.hellscraft.block.CheeseFenceBlock;
import net.mcreator.hellscraft.block.CarrotBricksBlock;
import net.mcreator.hellscraft.block.CarrotBrickWallBlock;
import net.mcreator.hellscraft.block.CarrotBrickStairsBlock;
import net.mcreator.hellscraft.block.CarrotBrickSlabBlock;
import net.mcreator.hellscraft.block.BlockOfVillagerBlock;
import net.mcreator.hellscraft.block.BlockOfSaltBlock;
import net.mcreator.hellscraft.block.BlockOfRottenFleshBlock;
import net.mcreator.hellscraft.block.BlockOfPoppyBlock;
import net.mcreator.hellscraft.block.BlockOfPopcornBlock;
import net.mcreator.hellscraft.block.BlockOfPinkSaltBlock;
import net.mcreator.hellscraft.block.BlockOfDandelionBlock;
import net.mcreator.hellscraft.block.BlockOfCornflowerBlock;
import net.mcreator.hellscraft.block.BlockOfCornBlock;
import net.mcreator.hellscraft.block.BlockOfCheeseBlock;
import net.mcreator.hellscraft.block.BlockOfCarrotBlock;
import net.mcreator.hellscraft.block.BlockOfButterBlock;
import net.mcreator.hellscraft.block.BlockOfBreadBlock;
import net.mcreator.hellscraft.block.BlockOfAzureBluetBlock;
import net.mcreator.hellscraft.block.BismuthBlock;
import net.mcreator.hellscraft.block.AgingBarrelBlock;
import net.mcreator.hellscraft.HellscraftMod;

public class HellscraftModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, HellscraftMod.MODID);
	public static final RegistryObject<Block> BLOCK_OF_CHEESE = REGISTRY.register("block_of_cheese", () -> new BlockOfCheeseBlock());
	public static final RegistryObject<Block> CHEESE_SLAB = REGISTRY.register("cheese_slab", () -> new CheeseSlabBlock());
	public static final RegistryObject<Block> CHEESE_STAIRS = REGISTRY.register("cheese_stairs", () -> new CheeseStairsBlock());
	public static final RegistryObject<Block> CHEESE_FENCE = REGISTRY.register("cheese_fence", () -> new CheeseFenceBlock());
	public static final RegistryObject<Block> PRESS = REGISTRY.register("press", () -> new PressBlock());
	public static final RegistryObject<Block> AGING_BARREL = REGISTRY.register("aging_barrel", () -> new AgingBarrelBlock());
	public static final RegistryObject<Block> BLOCK_OF_ROTTEN_FLESH = REGISTRY.register("block_of_rotten_flesh", () -> new BlockOfRottenFleshBlock());
	public static final RegistryObject<Block> BLOCK_OF_VILLAGER = REGISTRY.register("block_of_villager", () -> new BlockOfVillagerBlock());
	public static final RegistryObject<Block> QUICKSAND = REGISTRY.register("quicksand", () -> new QuicksandBlock());
	public static final RegistryObject<Block> NETHERSPICE_BLOCK = REGISTRY.register("netherspice_block", () -> new NetherspiceBlockBlock());
	public static final RegistryObject<Block> GUNK = REGISTRY.register("gunk", () -> new GunkBlock());
	public static final RegistryObject<Block> CORN_ORE = REGISTRY.register("corn_ore", () -> new CornOreBlock());
	public static final RegistryObject<Block> DEEPERSLATE = REGISTRY.register("deeperslate", () -> new DeeperslateBlock());
	public static final RegistryObject<Block> DEEPERSLATE_DIAMOND_ORE = REGISTRY.register("deeperslate_diamond_ore", () -> new DeeperslateDiamondOreBlock());
	public static final RegistryObject<Block> DEEPERSLATE_IRON_ORE = REGISTRY.register("deeperslate_iron_ore", () -> new DeeperslateIronOreBlock());
	public static final RegistryObject<Block> DARKSTEEL_ORE = REGISTRY.register("darksteel_ore", () -> new DarksteelOreBlock());
	public static final RegistryObject<Block> GREENSTONE = REGISTRY.register("greenstone", () -> new GreenstoneBlock());
	public static final RegistryObject<Block> GREENSTONE_SLAB = REGISTRY.register("greenstone_slab", () -> new GreenstoneSlabBlock());
	public static final RegistryObject<Block> GREENSTONE_STAIRS = REGISTRY.register("greenstone_stairs", () -> new GreenstoneStairsBlock());
	public static final RegistryObject<Block> GREENSTONE_BRICKS = REGISTRY.register("greenstone_bricks", () -> new GreenstoneBricksBlock());
	public static final RegistryObject<Block> GREENSTONE_BRICK_SLAB = REGISTRY.register("greenstone_brick_slab", () -> new GreenstoneBrickSlabBlock());
	public static final RegistryObject<Block> GREENSTONE_BRICK_STAIRS = REGISTRY.register("greenstone_brick_stairs", () -> new GreenstoneBrickStairsBlock());
	public static final RegistryObject<Block> GREENSTONE_BRICK_WALL = REGISTRY.register("greenstone_brick_wall", () -> new GreenstoneBrickWallBlock());
	public static final RegistryObject<Block> SMOOTH_GREENSTONE = REGISTRY.register("smooth_greenstone", () -> new SmoothGreenstoneBlock());
	public static final RegistryObject<Block> SMOOTH_GREENSTONE_SLAB = REGISTRY.register("smooth_greenstone_slab", () -> new SmoothGreenstoneSlabBlock());
	public static final RegistryObject<Block> CHISELED_GREENSTONE_BRICKS = REGISTRY.register("chiseled_greenstone_bricks", () -> new ChiseledGreenstoneBricksBlock());
	public static final RegistryObject<Block> COOLER_GREENSTONE = REGISTRY.register("cooler_greenstone", () -> new CoolerGreenstoneBlock());
	public static final RegistryObject<Block> PISS_NYLIUM = REGISTRY.register("piss_nylium", () -> new PissNyliumBlock());
	public static final RegistryObject<Block> PISS_STEM = REGISTRY.register("piss_stem", () -> new PissStemBlock());
	public static final RegistryObject<Block> STRIPPED_PISS_STEM = REGISTRY.register("stripped_piss_stem", () -> new StrippedPissStemBlock());
	public static final RegistryObject<Block> PISS_WART_BLOCK = REGISTRY.register("piss_wart_block", () -> new PissWartBlockBlock());
	public static final RegistryObject<Block> PISS_ROOTS = REGISTRY.register("piss_roots", () -> new PissRootsBlock());
	public static final RegistryObject<Block> PISS_MUSHROOM = REGISTRY.register("piss_mushroom", () -> new PissMushroomBlock());
	public static final RegistryObject<Block> KIDNEYSTONE = REGISTRY.register("kidneystone", () -> new KidneystoneBlock());
	public static final RegistryObject<Block> DARKWOOD_LOG = REGISTRY.register("darkwood_log", () -> new DarkwoodLogBlock());
	public static final RegistryObject<Block> SPAWN_EGG_ORE = REGISTRY.register("spawn_egg_ore", () -> new SpawnEggOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_SPAWN_EGG_ORE = REGISTRY.register("deepslate_spawn_egg_ore", () -> new DeepslateSpawnEggOreBlock());
	public static final RegistryObject<Block> ROCK_SALT = REGISTRY.register("rock_salt", () -> new RockSaltBlock());
	public static final RegistryObject<Block> ROCK_BUTTER = REGISTRY.register("rock_butter", () -> new RockButterBlock());
	public static final RegistryObject<Block> FISHMETAL_BLOCK = REGISTRY.register("fishmetal_block", () -> new FishmetalBlockBlock());
	public static final RegistryObject<Block> HARDSPICE = REGISTRY.register("hardspice", () -> new HardspiceBlock());
	public static final RegistryObject<Block> HARDSPICE_SLAB = REGISTRY.register("hardspice_slab", () -> new HardspiceSlabBlock());
	public static final RegistryObject<Block> HARDSPICE_STAIRS = REGISTRY.register("hardspice_stairs", () -> new HardspiceStairsBlock());
	public static final RegistryObject<Block> HARDSPICE_BRICKS = REGISTRY.register("hardspice_bricks", () -> new HardspiceBricksBlock());
	public static final RegistryObject<Block> HARDSPICE_BRICK_SLAB = REGISTRY.register("hardspice_brick_slab", () -> new HardspiceBrickSlabBlock());
	public static final RegistryObject<Block> HARDSPICE_BRICK_STAIRS = REGISTRY.register("hardspice_brick_stairs", () -> new HardspiceBrickStairsBlock());
	public static final RegistryObject<Block> HARDSPICE_BRICK_WALL = REGISTRY.register("hardspice_brick_wall", () -> new HardspiceBrickWallBlock());
	public static final RegistryObject<Block> SMOOTH_HARDSPICE = REGISTRY.register("smooth_hardspice", () -> new SmoothHardspiceBlock());
	public static final RegistryObject<Block> SMOOTH_HARDSPICE_SLAB = REGISTRY.register("smooth_hardspice_slab", () -> new SmoothHardspiceSlabBlock());
	public static final RegistryObject<Block> DARKSTEEL_BLOCK = REGISTRY.register("darksteel_block", () -> new DarksteelBlockBlock());
	public static final RegistryObject<Block> PISS_PLANKS = REGISTRY.register("piss_planks", () -> new PissPlanksBlock());
	public static final RegistryObject<Block> PISS_PLANK_SLAB = REGISTRY.register("piss_plank_slab", () -> new PissPlankSlabBlock());
	public static final RegistryObject<Block> PISS_PLANK_STAIRS = REGISTRY.register("piss_plank_stairs", () -> new PissPlankStairsBlock());
	public static final RegistryObject<Block> PISS_PLANK_FENCE = REGISTRY.register("piss_plank_fence", () -> new PissPlankFenceBlock());
	public static final RegistryObject<Block> PISS_PLANK_TRAPDOOR = REGISTRY.register("piss_plank_trapdoor", () -> new PissPlankTrapdoorBlock());
	public static final RegistryObject<Block> PISS_PLANK_DOOR = REGISTRY.register("piss_plank_door", () -> new PissPlankDoorBlock());
	public static final RegistryObject<Block> PISS_BUTTON = REGISTRY.register("piss_button", () -> new PissButtonBlock());
	public static final RegistryObject<Block> PISS_PRESSURE_PLATE = REGISTRY.register("piss_pressure_plate", () -> new PissPressurePlateBlock());
	public static final RegistryObject<Block> PISS_PLANK_FENCE_GATE = REGISTRY.register("piss_plank_fence_gate", () -> new PissPlankFenceGateBlock());
	public static final RegistryObject<Block> STRIPPED_DARKWOOD_LOG = REGISTRY.register("stripped_darkwood_log", () -> new StrippedDarkwoodLogBlock());
	public static final RegistryObject<Block> DARKWOOD_LEAVES = REGISTRY.register("darkwood_leaves", () -> new DarkwoodLeavesBlock());
	public static final RegistryObject<Block> DARKWOOD_PLANKS = REGISTRY.register("darkwood_planks", () -> new DarkwoodPlanksBlock());
	public static final RegistryObject<Block> DARKWOOD_SLAB = REGISTRY.register("darkwood_slab", () -> new DarkwoodSlabBlock());
	public static final RegistryObject<Block> DARKWOOD_STAIRS = REGISTRY.register("darkwood_stairs", () -> new DarkwoodStairsBlock());
	public static final RegistryObject<Block> DARKWOOD_FENCE = REGISTRY.register("darkwood_fence", () -> new DarkwoodFenceBlock());
	public static final RegistryObject<Block> DARKWOOD_FENCE_GATE = REGISTRY.register("darkwood_fence_gate", () -> new DarkwoodFenceGateBlock());
	public static final RegistryObject<Block> DARKWOOD_TRAPDOOR = REGISTRY.register("darkwood_trapdoor", () -> new DarkwoodTrapdoorBlock());
	public static final RegistryObject<Block> DARKWOOD_BUTTON = REGISTRY.register("darkwood_button", () -> new DarkwoodButtonBlock());
	public static final RegistryObject<Block> DARKWOOD_PRESSURE_PLATE = REGISTRY.register("darkwood_pressure_plate", () -> new DarkwoodPressurePlateBlock());
	public static final RegistryObject<Block> BLOCK_OF_CORN = REGISTRY.register("block_of_corn", () -> new BlockOfCornBlock());
	public static final RegistryObject<Block> WAXED_BLOCK_OF_CORN = REGISTRY.register("waxed_block_of_corn", () -> new WaxedBlockOfCornBlock());
	public static final RegistryObject<Block> POLISHED_BLOCK_OF_CORN = REGISTRY.register("polished_block_of_corn", () -> new PolishedBlockOfCornBlock());
	public static final RegistryObject<Block> POLISHED_CORN_SLAB = REGISTRY.register("polished_corn_slab", () -> new PolishedCornSlabBlock());
	public static final RegistryObject<Block> POLISHED_CORN_STAIRS = REGISTRY.register("polished_corn_stairs", () -> new PolishedCornStairsBlock());
	public static final RegistryObject<Block> POLISHED_CORN_WALL = REGISTRY.register("polished_corn_wall", () -> new PolishedCornWallBlock());
	public static final RegistryObject<Block> BLOCK_OF_POPCORN = REGISTRY.register("block_of_popcorn", () -> new BlockOfPopcornBlock());
	public static final RegistryObject<Block> POLISHED_BLOCK_OF_POPCORN = REGISTRY.register("polished_block_of_popcorn", () -> new PolishedBlockOfPopcornBlock());
	public static final RegistryObject<Block> POLISHED_POPCORN_SLAB = REGISTRY.register("polished_popcorn_slab", () -> new PolishedPopcornSlabBlock());
	public static final RegistryObject<Block> POLISHED_POPCORN_STAIRS = REGISTRY.register("polished_popcorn_stairs", () -> new PolishedPopcornStairsBlock());
	public static final RegistryObject<Block> POLISHED_POPCORN_WALL = REGISTRY.register("polished_popcorn_wall", () -> new PolishedPopcornWallBlock());
	public static final RegistryObject<Block> BLOCK_OF_SALT = REGISTRY.register("block_of_salt", () -> new BlockOfSaltBlock());
	public static final RegistryObject<Block> BLOCK_OF_BUTTER = REGISTRY.register("block_of_butter", () -> new BlockOfButterBlock());
	public static final RegistryObject<Block> BLOCK_OF_PINK_SALT = REGISTRY.register("block_of_pink_salt", () -> new BlockOfPinkSaltBlock());
	public static final RegistryObject<Block> SALT_LAMP = REGISTRY.register("salt_lamp", () -> new SaltLampBlock());
	public static final RegistryObject<Block> PRESS_A = REGISTRY.register("press_a", () -> new PressABlock());
	public static final RegistryObject<Block> STONE_BLOCK = REGISTRY.register("stone_block", () -> new StoneBlockBlock());
	public static final RegistryObject<Block> BLOCK_OF_BREAD = REGISTRY.register("block_of_bread", () -> new BlockOfBreadBlock());
	public static final RegistryObject<Block> BISMUTH = REGISTRY.register("bismuth", () -> new BismuthBlock());
	public static final RegistryObject<Block> CHUCKITE = REGISTRY.register("chuckite", () -> new ChuckiteBlock());
	public static final RegistryObject<Block> CHUCKITE_SLAB = REGISTRY.register("chuckite_slab", () -> new ChuckiteSlabBlock());
	public static final RegistryObject<Block> CHUCKITE_STAIRS = REGISTRY.register("chuckite_stairs", () -> new ChuckiteStairsBlock());
	public static final RegistryObject<Block> POLISHED_CHUCKITE = REGISTRY.register("polished_chuckite", () -> new PolishedChuckiteBlock());
	public static final RegistryObject<Block> POLISHED_CHUCKITE_SLAB = REGISTRY.register("polished_chuckite_slab", () -> new PolishedChuckiteSlabBlock());
	public static final RegistryObject<Block> POLISHED_CHUCKITE_STAIRS = REGISTRY.register("polished_chuckite_stairs", () -> new PolishedChuckiteStairsBlock());
	public static final RegistryObject<Block> POLISHED_DEEPERSLATE = REGISTRY.register("polished_deeperslate", () -> new PolishedDeeperslateBlock());
	public static final RegistryObject<Block> DEEPERSLATE_BRICKS = REGISTRY.register("deeperslate_bricks", () -> new DeeperslateBricksBlock());
	public static final RegistryObject<Block> CHISELED_DEEPERSLATE = REGISTRY.register("chiseled_deeperslate", () -> new ChiseledDeeperslateBlock());
	public static final RegistryObject<Block> DEEPERSLATE_BRICK_SLAB = REGISTRY.register("deeperslate_brick_slab", () -> new DeeperslateBrickSlabBlock());
	public static final RegistryObject<Block> DEEPERSLATE_BRICK_STAIRS = REGISTRY.register("deeperslate_brick_stairs", () -> new DeeperslateBrickStairsBlock());
	public static final RegistryObject<Block> DEEPERSLATE_BRICK_WALL = REGISTRY.register("deeperslate_brick_wall", () -> new DeeperslateBrickWallBlock());
	public static final RegistryObject<Block> JEWELED_DEEPERSLATE = REGISTRY.register("jeweled_deeperslate", () -> new JeweledDeeperslateBlock());
	public static final RegistryObject<Block> JEWELED_DEEPERSLATE_BRICKS = REGISTRY.register("jeweled_deeperslate_bricks", () -> new JeweledDeeperslateBricksBlock());
	public static final RegistryObject<Block> CHISELED_JEWELED_DEEPERSLATE = REGISTRY.register("chiseled_jeweled_deeperslate", () -> new ChiseledJeweledDeeperslateBlock());
	public static final RegistryObject<Block> GILDED_DEEPERSLATE = REGISTRY.register("gilded_deeperslate", () -> new GildedDeeperslateBlock());
	public static final RegistryObject<Block> GILDED_DEEPERSLATE_BRICKS = REGISTRY.register("gilded_deeperslate_bricks", () -> new GildedDeeperslateBricksBlock());
	public static final RegistryObject<Block> CHISELED_GILDED_DEEPERSLATE = REGISTRY.register("chiseled_gilded_deeperslate", () -> new ChiseledGildedDeeperslateBlock());
	public static final RegistryObject<Block> GALVANIC_DEEPERSLATE = REGISTRY.register("galvanic_deeperslate", () -> new GalvanicDeeperslateBlock());
	public static final RegistryObject<Block> GALVANIC_DEEPERSLATE_BRICKS = REGISTRY.register("galvanic_deeperslate_bricks", () -> new GalvanicDeepslateBricksBlock());
	public static final RegistryObject<Block> CHISLED_GALVANIC_DEEPERSLATE = REGISTRY.register("chisled_galvanic_deeperslate", () -> new ChisledGalvanicDeeperslateBlock());
	public static final RegistryObject<Block> POLISHED_KIDNEYSTONE = REGISTRY.register("polished_kidneystone", () -> new PolishedKidneystoneBlock());
	public static final RegistryObject<Block> KIDNEYSTONE_BRICKS = REGISTRY.register("kidneystone_bricks", () -> new KidneystoneBricksBlock());
	public static final RegistryObject<Block> CRACKED_KIDNEYSTONE_BRICKS = REGISTRY.register("cracked_kidneystone_bricks", () -> new CrackedKidneystoneBricksBlock());
	public static final RegistryObject<Block> CHISELED_KIDNEYSTONE = REGISTRY.register("chiseled_kidneystone", () -> new ChiseledKidneystoneBlock());
	public static final RegistryObject<Block> ENDGRANITE = REGISTRY.register("endgranite", () -> new EndgraniteBlock());
	public static final RegistryObject<Block> ENDIORITE = REGISTRY.register("endiorite", () -> new EndioriteBlock());
	public static final RegistryObject<Block> ENDERSITE = REGISTRY.register("endersite", () -> new EndersiteBlock());
	public static final RegistryObject<Block> END_FLUID = REGISTRY.register("end_fluid", () -> new EndFluidBlock());
	public static final RegistryObject<Block> POLISHED_ENDGRANITE = REGISTRY.register("polished_endgranite", () -> new PolishedEndgraniteBlock());
	public static final RegistryObject<Block> POLISHED_ENDIORITE = REGISTRY.register("polished_endiorite", () -> new PolishedEndioriteBlock());
	public static final RegistryObject<Block> POLISHED_ENDERSITE = REGISTRY.register("polished_endersite", () -> new PolishedEndersiteBlock());
	public static final RegistryObject<Block> GREASE = REGISTRY.register("grease", () -> new GreaseBlock());
	public static final RegistryObject<Block> URANIUM_ORE = REGISTRY.register("uranium_ore", () -> new UraniumOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_URANIUM_ORE = REGISTRY.register("deepslate_uranium_ore", () -> new DeepslateUraniumOreBlock());
	public static final RegistryObject<Block> BLOCK_OF_CARROT = REGISTRY.register("block_of_carrot", () -> new BlockOfCarrotBlock());
	public static final RegistryObject<Block> CARROT_BRICKS = REGISTRY.register("carrot_bricks", () -> new CarrotBricksBlock());
	public static final RegistryObject<Block> CARROT_BRICK_SLAB = REGISTRY.register("carrot_brick_slab", () -> new CarrotBrickSlabBlock());
	public static final RegistryObject<Block> CARROT_BRICK_STAIRS = REGISTRY.register("carrot_brick_stairs", () -> new CarrotBrickStairsBlock());
	public static final RegistryObject<Block> CARROT_BRICK_WALL = REGISTRY.register("carrot_brick_wall", () -> new CarrotBrickWallBlock());
	public static final RegistryObject<Block> BLOCK_OF_DANDELION = REGISTRY.register("block_of_dandelion", () -> new BlockOfDandelionBlock());
	public static final RegistryObject<Block> GRUD = REGISTRY.register("grud", () -> new GrudBlock());
	public static final RegistryObject<Block> VANTABLOCK = REGISTRY.register("vantablock", () -> new VantablockBlock());
	public static final RegistryObject<Block> BLOCK_OF_POPPY = REGISTRY.register("block_of_poppy", () -> new BlockOfPoppyBlock());
	public static final RegistryObject<Block> BLOCK_OF_CORNFLOWER = REGISTRY.register("block_of_cornflower", () -> new BlockOfCornflowerBlock());
	public static final RegistryObject<Block> BLOCK_OF_AZURE_BLUET = REGISTRY.register("block_of_azure_bluet", () -> new BlockOfAzureBluetBlock());
	public static final RegistryObject<Block> MUSHRACK = REGISTRY.register("mushrack", () -> new MushrackBlock());
}
